port: 8080
access_log: true
token_user_search: sub
token_url: https://auth.example.com/token
auth_flow: password
check_scope: true
cors:
  enabled: true
  allow_origin:
    - "*"
  methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  headers:
    - "Accept"
    - "Content-Type"
    - "Authorization"
    - "X-Requested-With"
  max_age: 86400
plugin_configs:
  - ./test.yaml
plugins:
  sqlite:
    title: "SQLite API"
    uri: sqlite://./test.db
    enable_cache: true
  postgres:
    title: "Postgres API"
    uri: postgres://postgres:root@localhost:5433/easyrestdb?maxOpenConns=100&maxIdleConns=25&connMaxLifetime=5&connMaxIdleTime=10&timeout=30&bulkThreshold=100&sslmode=disable&search_path=public&autoCleanup=true
    enable_cache: true
  mysql:
    title: "MySQL API"
    uri: mysql://root:root@localhost:3307/easyrestdb?parseTime=true&autoCleanup=true
    enable_cache: true
  redis:
    uri: redis://localhost:6379/1
  # test:
  #   uri: sqlite://./test.db
anon_claims:
  role: "anonymous"
  sub: 0
