name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Download Dependencies
        run: go mod download

      - name: Build Release Binaries
        run: |
          for GOOS in linux darwin; do 
            for GOARCH in amd64 arm64; do 
              for BIN in $(ls cmd); do 
                echo "Building $BIN for $GOOS/$GOARCH..."
                BUILD_DIR=release GOOS=$GOOS GOARCH=$GOARCH make $BIN \
                  && mv release/easyrest-$BIN release/easyrest-$BIN-$GOOS-$GOARCH;
              done; 
            done; 
          done

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get lowercase repository name
        id: string_ops
        run: echo "repository_lowercase=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ steps.string_ops.outputs.repository_lowercase }}:${{ github.ref_name }}
            ghcr.io/${{ steps.string_ops.outputs.repository_lowercase }}:latest

      - name: Get Commit Message (without first line)
        id: commit
        run: |
          COMMIT_BODY=$(git log -1 --pretty=format:"%b")
          echo "message<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMIT_BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: ${{ steps.commit.outputs.message }}
          artifacts: release/*
