name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build Release Binaries
        run: |
          mkdir -p release
          for GOOS in linux darwin; do 
            for GOARCH in amd64 arm64; do 
              for BIN in plugin-sqlite server; do 
                echo "Building $BIN for $GOOS/$GOARCH..."
                BUILD_DIR=release GOOS=$GOOS GOARCH=$GOARCH make $BIN \
                  && mv release/easyrest-$BIN release/easyrest-$BIN-$GOOS-$GOARCH;
              done; 
            done; 
          done

      - name: Get Commit Message (without first line)
        id: commit
        run: |
          COMMIT_BODY=$(git log -1 --pretty=format:"%b")
          echo "message<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMIT_BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: ${{ steps.commit.outputs.message }}
          artifacts: release/*
